site_name: Looper
site_logo: img/looper_logo_dark.svg
site_url: http://looper.databio.org/
repo_url: http://github.com/pepkit/looper
pypi_name: loopercli

nav:
  - Getting Started: 
    - Introduction: README.md
    - Features at-a-glance: features.md
    - Hello world: hello-world.md
  - How-to guides:    
    - Defining a project: defining-a-project.md
    - Running a pipeline: running-a-pipeline.md
    - Initializing a repository: initialize.md
    - Parameterizing pipelines: parameterizing-pipelines.md
    - Running on a cluster: running-on-a-cluster.md
    - Grouping many jobs into one: grouping-jobs.md
    - Running jobs in containers: containers.md
    - Handling multiple input files: how-to-merge-inputs.md
    - Running multiple pipelines: multiple-pipelines.md
    - Writing a pipeline interface: writing-a-pipeline-interface.md
  - Reference:
    - Pipeline interface specification: pipeline-interface-specification.md
    - Pipeline tiers: pipeline-tiers.md
    - Concentric templates: concentric-templates.md
    - Pre-submission hooks system: pre-submission-hooks.md
    - Looper variable namespaces: variable-namespaces.md
    - Usage: usage.md
    - Configuration files: config-files.md
    - API: autodoc_build/looper.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      autodoc_package: "looper"
      no_top_level: true
  - search
