#!/bin/bash
#SBATCH --job-name='{JOBNAME}'
#SBATCH --output='{LOGFILE}'
#SBATCH --mem='{MEM}'
#SBATCH --cpus-per-task='{CORES}'
#SBATCH --time='{TIME}'
#SBATCH --partition='{PARTITION}'
#SBATCH -m block
#SBATCH --ntasks=1

echo 'Compute node:' `hostname`
echo 'Start time:' `date +'%Y-%m-%d %T'`

{PRE_COMMAND}

apptainer instance start {APPTAINER_ARGS} {APPTAINER_IMAGE} {JOBNAME}_image
srun apptainer exec instance://{JOBNAME}_image {CODE}

apptainer instance stop {JOBNAME}_image

{POST_COMMAND}
