#!/bin/bash
#SBATCH --job-name='TEST2_sample2'
#SBATCH --output='../output/submission/TEST2_sample2.log'
#SBATCH --mem='{MEM}'
#SBATCH --cpus-per-task='{CORES}'
#SBATCH --time='{TIME}'
#SBATCH --partition='standard'
#SBATCH -m block
#SBATCH --ntasks=1
#SBATCH --open-mode=append

echo 'Compute node:' `hostname`
echo 'Start time:' `date +'%Y-%m-%d %T'`

cmd="pipelines/other_pipeline2.py --sample-name sample2 "

y=`echo "$cmd" | sed -e 's/^/srun /'`
eval "$y"
