# Use this to change your cluster manager (SLURM, SGE, LFS, etc).
# Relative paths are relative to this compute environment configuration file.
# Compute resource parameters fill the submission_template file's fields.
adapters:
  CODE: looper.command
  JOBNAME: looper.job_name
  CORES: compute.cores
  LOGFILE: looper.log_file
  TIME: compute.time
  MEM: compute.mem
  DOCKER_ARGS: compute.docker_args
  DOCKER_IMAGE: compute.docker_image
  APPTAINER_IMAGE: compute.apptainer_image
  APPTAINER_ARGS: compute.apptainer_args
  BULKER_CRATE: compute.bulker_crate
  PRE_COMMAND: compute.pre_command
  POST_COMMAND: compute.post_command
compute_packages:
  default:
    submission_template: divvy_templates/localhost_template.sub
    submission_command: .
    pre_command: ""
    post_command: ""
  local:
    submission_template: divvy_templates/localhost_template.sub
    submission_command: .
    pre_command: ""
    post_command: ""
  slurm:
    submission_template: divvy_templates/slurm_template.sub
    submission_command: sbatch
    pre_command: ""
    post_command: ""
  sge:
    submission_template: divvy_templates/sge_template.sub
    submission_command: qsub
    pre_command: ""
    post_command: ""
  apptainer:
    submission_template: divvy_templates/localhost_apptainer_template.sub
    submission_command: .
    apptainer_args: ""
    pre_command: ""
    post_command: ""
  apptainer_slurm:
    submission_template: divvy_templates/slurm_apptainer_template.sub
    submission_command: sbatch
    apptainer_args: ""
    pre_command: ""
    post_command: ""
  bulker_local:
    submission_template: divvy_templates/localhost_bulker_template.sub
    submission_command: sh
    pre_command: ""
    post_command: ""
  bulker_slurm:
    submission_template: divvy_templates/bulker_slurm_template.sub
    submission_command: sbatch
    pre_command: ""
    post_command: ""
  docker:
    submission_template: divvy_templates/localhost_docker_template.sub
    submission_command: .
    docker_args: |
      --user=$(id -u):$(id -g) \
      --env="DISPLAY" \
      --volume="/etc/group:/etc/group:ro" \
      --volume="/etc/passwd:/etc/passwd:ro" \
      --volume="/etc/shadow:/etc/shadow:ro"  \
      --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
      --workdir="`pwd`" \
    pre_command: ""
    post_command: ""
